# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Estimate item parameter for binary{0,1} response data.
#'1PL,2PL,3PL,Bayes1PL,Bayes2PL and multigroup estimation is avairable now.
#'@param x an item response data which class is data.frame object.
#'@param model Character.U can select which one, "1PL","2PL","3PL".
#'@param N the number of nodes in integration
#'@param eMLL a convergence criteria(CC) forf marginal log likelihood.
#'@param eEM a CC in EM cycle.
#'@param eM a CC in M step.
#'@param emu a CC for population distribution mean.
#'@param fc0 a column of first item response
#'@param ng the number of groups
#'@param gc0 a column of group.
#'@param D a scaling constant.
#'@param fix If 1, fix population distribution mean and sigma each EM cycle.
#'@param print How much information you want to display? from 1 to 3. The larger, more information is displayed.
#'@param ic a initial value for guessing parameter.
#'@param max a maximum value of theta in integration.
#'@param min a minimum value of theta in integration.
#'@param mu a hyperparameter for theta dist.
#'@param sigma same as above.
#'@param Bayes If 1, marginal Bayesian estimation runs.
#'@param mu_a a hyperparameter of log normal dist for slope parameter.
#'@param sigma_a same as above.
#'@param mu_b a hyperparameter of normal dist for location parameter.
#'@param sigma_b same as above.
#'@param mu_c a hyperparameter for lower asymptote parameter.
#'@param w_c weight of a Beta dist.
#'@param min_a a minimum value of slope parameter.
#'@param maxabs_b a maximum absolute value of location parameter.
#'@param maxiter_em a maximul iteration time for EM cycle.
#'@param maxiter_j a maximul iteration time for Newton Raphton in M step.
#'@param maxskip_j Dont use.
#'@param rm_list a vector of item U want to remove for estimation. NOT list.
#'@param thdist Dont use.
#'@param e_ell a CC of expected log likelihood.
#'@param EM_dist If 1, calculate esimated population distribution by EM argorithm.
#' @export
estip <- function(x, model = "2PL", N = 31L, eMLL = 1e-6, eEM = 1e-4, eM = 1e-3, emu = 1e-4, fc0 = 2L, ng = 1L, gc0 = 2L, D = 1.702, fix = 1L, print = 0L, ic = 1/5, max = 6.0, min = -6.0, mu = 0, sigma = 1, Bayes = 0L, mu_a = 0, sigma_a = 1, mu_b = 0, sigma_b = 2, mu_c = 4/13, w_c = 13, min_a = 0.1, maxabs_b = 20, maxiter_em = 200L, maxiter_j = 20L, maxskip_j = 5L, rm_list = as.character( c("NONE")), thdist = "normal", e_ell = 1L, EM_dist = 1L) {
    .Call(`_irtfun2_estip`, x, model, N, eMLL, eEM, eM, emu, fc0, ng, gc0, D, fix, print, ic, max, min, mu, sigma, Bayes, mu_a, sigma_a, mu_b, sigma_b, mu_c, w_c, min_a, maxabs_b, maxiter_em, maxiter_j, maxskip_j, rm_list, thdist, e_ell, EM_dist)
}

